/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebDesignDevelopmentRouteImport } from './routes/web-design-development'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TechnologyConsultingRouteImport } from './routes/technology-consulting'
import { Route as TechnicalInfrastructureRouteImport } from './routes/technical-infrastructure'
import { Route as OngoingPartnershipRouteImport } from './routes/ongoing-partnership'
import { Route as MaintenanceSupportRouteImport } from './routes/maintenance-support'
import { Route as HostingServerSetupRouteImport } from './routes/hosting-server-setup'
import { Route as DigitalPresenceRouteImport } from './routes/digital-presence'
import { Route as CustomDevelopmentRouteImport } from './routes/custom-development'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessAutomationRouteImport } from './routes/business-automation'
import { Route as AiBusinessAutomationRouteImport } from './routes/ai-business-automation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WebDesignDevelopmentRoute = WebDesignDevelopmentRouteImport.update({
  id: '/web-design-development',
  path: '/web-design-development',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyConsultingRoute = TechnologyConsultingRouteImport.update({
  id: '/technology-consulting',
  path: '/technology-consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalInfrastructureRoute = TechnicalInfrastructureRouteImport.update({
  id: '/technical-infrastructure',
  path: '/technical-infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const OngoingPartnershipRoute = OngoingPartnershipRouteImport.update({
  id: '/ongoing-partnership',
  path: '/ongoing-partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceSupportRoute = MaintenanceSupportRouteImport.update({
  id: '/maintenance-support',
  path: '/maintenance-support',
  getParentRoute: () => rootRouteImport,
} as any)
const HostingServerSetupRoute = HostingServerSetupRouteImport.update({
  id: '/hosting-server-setup',
  path: '/hosting-server-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalPresenceRoute = DigitalPresenceRouteImport.update({
  id: '/digital-presence',
  path: '/digital-presence',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomDevelopmentRoute = CustomDevelopmentRouteImport.update({
  id: '/custom-development',
  path: '/custom-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAutomationRoute = BusinessAutomationRouteImport.update({
  id: '/business-automation',
  path: '/business-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBusinessAutomationRoute = AiBusinessAutomationRouteImport.update({
  id: '/ai-business-automation',
  path: '/ai-business-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-business-automation': typeof AiBusinessAutomationRoute
  '/business-automation': typeof BusinessAutomationRoute
  '/contact': typeof ContactRoute
  '/custom-development': typeof CustomDevelopmentRoute
  '/digital-presence': typeof DigitalPresenceRoute
  '/hosting-server-setup': typeof HostingServerSetupRoute
  '/maintenance-support': typeof MaintenanceSupportRoute
  '/ongoing-partnership': typeof OngoingPartnershipRoute
  '/technical-infrastructure': typeof TechnicalInfrastructureRoute
  '/technology-consulting': typeof TechnologyConsultingRoute
  '/terms': typeof TermsRoute
  '/web-design-development': typeof WebDesignDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-business-automation': typeof AiBusinessAutomationRoute
  '/business-automation': typeof BusinessAutomationRoute
  '/contact': typeof ContactRoute
  '/custom-development': typeof CustomDevelopmentRoute
  '/digital-presence': typeof DigitalPresenceRoute
  '/hosting-server-setup': typeof HostingServerSetupRoute
  '/maintenance-support': typeof MaintenanceSupportRoute
  '/ongoing-partnership': typeof OngoingPartnershipRoute
  '/technical-infrastructure': typeof TechnicalInfrastructureRoute
  '/technology-consulting': typeof TechnologyConsultingRoute
  '/terms': typeof TermsRoute
  '/web-design-development': typeof WebDesignDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-business-automation': typeof AiBusinessAutomationRoute
  '/business-automation': typeof BusinessAutomationRoute
  '/contact': typeof ContactRoute
  '/custom-development': typeof CustomDevelopmentRoute
  '/digital-presence': typeof DigitalPresenceRoute
  '/hosting-server-setup': typeof HostingServerSetupRoute
  '/maintenance-support': typeof MaintenanceSupportRoute
  '/ongoing-partnership': typeof OngoingPartnershipRoute
  '/technical-infrastructure': typeof TechnicalInfrastructureRoute
  '/technology-consulting': typeof TechnologyConsultingRoute
  '/terms': typeof TermsRoute
  '/web-design-development': typeof WebDesignDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-business-automation'
    | '/business-automation'
    | '/contact'
    | '/custom-development'
    | '/digital-presence'
    | '/hosting-server-setup'
    | '/maintenance-support'
    | '/ongoing-partnership'
    | '/technical-infrastructure'
    | '/technology-consulting'
    | '/terms'
    | '/web-design-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-business-automation'
    | '/business-automation'
    | '/contact'
    | '/custom-development'
    | '/digital-presence'
    | '/hosting-server-setup'
    | '/maintenance-support'
    | '/ongoing-partnership'
    | '/technical-infrastructure'
    | '/technology-consulting'
    | '/terms'
    | '/web-design-development'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-business-automation'
    | '/business-automation'
    | '/contact'
    | '/custom-development'
    | '/digital-presence'
    | '/hosting-server-setup'
    | '/maintenance-support'
    | '/ongoing-partnership'
    | '/technical-infrastructure'
    | '/technology-consulting'
    | '/terms'
    | '/web-design-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiBusinessAutomationRoute: typeof AiBusinessAutomationRoute
  BusinessAutomationRoute: typeof BusinessAutomationRoute
  ContactRoute: typeof ContactRoute
  CustomDevelopmentRoute: typeof CustomDevelopmentRoute
  DigitalPresenceRoute: typeof DigitalPresenceRoute
  HostingServerSetupRoute: typeof HostingServerSetupRoute
  MaintenanceSupportRoute: typeof MaintenanceSupportRoute
  OngoingPartnershipRoute: typeof OngoingPartnershipRoute
  TechnicalInfrastructureRoute: typeof TechnicalInfrastructureRoute
  TechnologyConsultingRoute: typeof TechnologyConsultingRoute
  TermsRoute: typeof TermsRoute
  WebDesignDevelopmentRoute: typeof WebDesignDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-design-development': {
      id: '/web-design-development'
      path: '/web-design-development'
      fullPath: '/web-design-development'
      preLoaderRoute: typeof WebDesignDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology-consulting': {
      id: '/technology-consulting'
      path: '/technology-consulting'
      fullPath: '/technology-consulting'
      preLoaderRoute: typeof TechnologyConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-infrastructure': {
      id: '/technical-infrastructure'
      path: '/technical-infrastructure'
      fullPath: '/technical-infrastructure'
      preLoaderRoute: typeof TechnicalInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ongoing-partnership': {
      id: '/ongoing-partnership'
      path: '/ongoing-partnership'
      fullPath: '/ongoing-partnership'
      preLoaderRoute: typeof OngoingPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance-support': {
      id: '/maintenance-support'
      path: '/maintenance-support'
      fullPath: '/maintenance-support'
      preLoaderRoute: typeof MaintenanceSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosting-server-setup': {
      id: '/hosting-server-setup'
      path: '/hosting-server-setup'
      fullPath: '/hosting-server-setup'
      preLoaderRoute: typeof HostingServerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-presence': {
      id: '/digital-presence'
      path: '/digital-presence'
      fullPath: '/digital-presence'
      preLoaderRoute: typeof DigitalPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-development': {
      id: '/custom-development'
      path: '/custom-development'
      fullPath: '/custom-development'
      preLoaderRoute: typeof CustomDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-automation': {
      id: '/business-automation'
      path: '/business-automation'
      fullPath: '/business-automation'
      preLoaderRoute: typeof BusinessAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-business-automation': {
      id: '/ai-business-automation'
      path: '/ai-business-automation'
      fullPath: '/ai-business-automation'
      preLoaderRoute: typeof AiBusinessAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiBusinessAutomationRoute: AiBusinessAutomationRoute,
  BusinessAutomationRoute: BusinessAutomationRoute,
  ContactRoute: ContactRoute,
  CustomDevelopmentRoute: CustomDevelopmentRoute,
  DigitalPresenceRoute: DigitalPresenceRoute,
  HostingServerSetupRoute: HostingServerSetupRoute,
  MaintenanceSupportRoute: MaintenanceSupportRoute,
  OngoingPartnershipRoute: OngoingPartnershipRoute,
  TechnicalInfrastructureRoute: TechnicalInfrastructureRoute,
  TechnologyConsultingRoute: TechnologyConsultingRoute,
  TermsRoute: TermsRoute,
  WebDesignDevelopmentRoute: WebDesignDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
